version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    target-branch: "dev"
    groups:
      angular:
        patterns:
          - '@angular*'
      blocknote:
        patterns:
          - '@blocknote/*'
      fullcalendar:
        patterns:
          - '@fullcalendar/*'
      html-eslint:
        patterns:
          - '@html-eslint/*'
      ng-select:
        patterns:
          - '@ng-select/*'
      appsignal:
        patterns:
          - '@appsignal/*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
    ignore:
      - dependency-name: "@angular*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@openproject/octicons"
      - dependency-name: "@openproject/primer-view-components"
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "dev"
    groups:
      aws-gems:
        patterns:
          - "aws-*"
    ignore:
      - dependency-name: "openproject-octicons"
      - dependency-name: "openproject-octicons_helper"
      - dependency-name: "openproject-primer_view_components"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
