name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

# explicitly configure permissions, in case your GITHUB_TOKEN workflow permissions are set to read-only in repository settings
permissions:
  actions: write
  contents: read # this can be 'read' if the signatures are in remote repository
  pull-requests: write
  statuses: write

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.OPENPROJECTCI_GH_LEGAL_TOKEN }}
        with:
          path-to-signatures: 'contributor-license-agreement/signatures/version1.json'
          path-to-document: 'https://www.openproject.org/legal/contributor-license-agreement' # e.g. a CLA or a DCO document
          # branch should not be protected
          branch: 'main'
          allowlist: >
            Copilot,
            Daten-David,
            EinLama,
            HDinger,
            JanKeppler,
            Kharonus,
            Lucas-Knechtel,
            MayaBerd,
            NobodysNightmare,
            RobinWagner,
            akabiru,
            as-op,
            astock2,
            ba1ash,
            birthe,
            brunopagno,
            bsatarnejad,
            cbliard,
            copilot[bot],
            copilot-swe-agent[bot],
            corinnaguenther,
            crohr,
            dependabot[bot],
            dombesz,
            dominic-braeunlein,
            dsteiner,
            dtohmucu,
            gleone-art,
            ihor-khomenko,
            judithroth,
            klaustopher,
            kluedecke,
            lindenthal,
            machisuji,
            marcalcobe,
            mereghost,
            mrmir,
            myabc,
            oliverguenther,
            openprojectci,
            psatyal,
            samachon,
            shiroginne,
            toy,
            ulferts,
            vonTronje,
            vspielau,
            wielinde,
            yanzubrytskyi

          # the followings are the optional inputs - If the optional inputs are not given, then default values will be taken
          remote-organization-name: opf
          remote-repository-name: legal
          #create-file-commit-message: 'For example: Creating file for storing CLA Signatures'
          #signed-commit-message: 'For example: $contributorName has signed the CLA in $owner/$repo#$pullRequestNo'
          #custom-notsigned-prcomment: 'pull request comment with Introductory message to ask new contributors to sign'
          #custom-pr-sign-comment: 'The signature to be committed in order to sign the CLA'
          #custom-allsigned-prcomment: 'pull request comment when all contributors has signed, defaults to **CLA Assistant Lite bot** All Contributors have signed the CLA.'
          #lock-pullrequest-aftermerge: false - if you don't want this bot to automatically lock the pull request after merging (default - true)
          #use-dco-flag: true - If you are using DCO instead of CLA
