name: continuous-delivery
on:
  push:
    branches:
      - dev
      - release/*
      - stable/*
permissions:
  contents: read

jobs:
  trigger_downstream_workflow:
    permissions:
      contents: none
    if: github.repository_owner == 'opf'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Flavours workflow
        env:
          TOKEN: ${{ secrets.OPENPROJECTCI_FLAVOUR_TRIGGER_TOKEN }}
          REPOSITORY: opf/openproject-flavours
          WORKFLOW_ID: ci.yml
          REF_NAME: ${{ github.ref_name }}
        run: |
          PAYLOAD=$(jq -n --arg ref "$REF_NAME" '{"ref": "dev", "inputs": {"ref": $ref}}')
          curl -i --fail-with-body -H"authorization: Bearer $TOKEN" \
            -XPOST -H"Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPOSITORY/actions/workflows/$WORKFLOW_ID/dispatches \
            -d "$PAYLOAD"
