name: Docker / Tagged builds

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      tag:
        description: "The tag to release. Note that this happens by default on the tag push. Only run this action when something went wrong!"
        required: false

jobs:
  compute-inputs:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.compute.outputs.tag }}
      branch: ${{ steps.compute.outputs.branch }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
      - name: Compute tags and branch
        id: compute
        env:
          EVENT_NAME: ${{ github.event_name }}
          INPUT_TAG: ${{ inputs.tag }}
        run: |
          if [[ "$EVENT_NAME" == 'push' ]]; then
            # Tag push e.g. refs/tags/v16.3.0 => v16.3.0
            TAG_REF="${GITHUB_REF#refs/tags/}"
            BRANCH_REF="$GITHUB_REF"
          elif [[ "$EVENT_NAME" == 'workflow_dispatch' && -n "$INPUT_TAG" ]]; then
            # Manual dispatch with tag
            TAG_REF="$INPUT_TAG"
            BRANCH_REF="$INPUT_TAG"
          else
            # Fallback to dev
            TAG_REF="dev"
            BRANCH_REF="dev"
          fi

          echo "branch=$BRANCH_REF" | tee -a "$GITHUB_OUTPUT"
          echo "tag=$TAG_REF" | tee -a "$GITHUB_OUTPUT"

  build:
    needs: compute-inputs
    uses: ./.github/workflows/docker.yml
    with:
      branch: ${{ needs.compute-inputs.outputs.branch }}
      tag: ${{ needs.compute-inputs.outputs.tag }}
    secrets: inherit

  trigger_helm_release:
    if: ${{ github.repository == 'opf/openproject' }}
    needs: [compute-inputs, build]
    permissions:
      contents: none
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Helm charts release
        env:
          TOKEN: ${{ secrets.OPENPROJECTCI_HELM_CHARTS_TRIGGER_TOKEN }}
          REPOSITORY: opf/helm-charts
          WORKFLOW_ID: core_release.yml
          TAG: ${{ needs.compute-inputs.outputs.tag }}
        run: |
          PAYLOAD=$(jq -n --arg tag "$TAG" '{"ref": "main", "inputs": {"tag": $tag}}')
          curl -i --fail-with-body -H"authorization: Bearer $TOKEN" \
            -XPOST -H"Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$REPOSITORY/actions/workflows/$WORKFLOW_ID/dispatches \
            -d "$PAYLOAD"
